module.exports = [
  { tag: "Tss" },
  { tag: "Ja" },
  { tag: "Cs" },
  { tag: "Js" },
  { tag: "Go" },
  { tag: "Rust" },
  { tag: "Asd" },
  { tag: "Jest" },
  { tag: "Css" },
  { tag: "Hs" },
  { tag: "Express" },
  { tag: "Carpet" },
  { tag: "Home" },
];
